### ISSUE TITLE
Webserver is not working

### ISSUE THREAD

**Issue by ChungmaruQ** [lidawei1975/deep#1]
Webserver just returned 404 found error.

http://spin.ccic.osu.edu/index.php/deep_picker

**Comment by lidawei1975** [comment]
Hi,

Thanks for reaching out. I tried just now and it is working fine. Maybe you
need to clear the cache first?

best,
Dawei

**Comment by ChungmaruQ** [comment]
Hmm It is weird..
I tested with other environment but got same results..
http://spin.ccic.osu.edu/index.php/null/null

**Comment by lidawei1975** [comment]
Hi,

If nothing is working from spin.ccic.osu.edu, I suspect it is a cookie
issue. Could you please click the "Not secure" (just before web address in
your browser address bar) then clear all cookies from "spin.ccic.osu.edu"
and try again?

best,
Dawei

**Comment by ChungmaruQ** [comment]
Hmm I don't know the reason...
I did it as your suggestion..
But it is still same..
My friends from German have same problem.

**Comment by lidawei1975** [comment]
It should work now.

Dawei

**Comment by ChungmaruQ** [comment]
It works!
Thanks!
